[tool.poetry]
name = "python-mastery"
version = "0.1.0"
description = ""
authors = ["Roberts Scetinins <skenline@inbox.lv>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
